name: Deploy to Google Cloud

on:
  push:
    branches: [cd]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install firebase-tools
        run: npm install -g firebase-tools
      - name: Authenticate to Google
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: true
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy functions
        run: npm run deploy
      - name: List files in repo
        if: always()
        run: ls