name: Deploy to Google Cloud

on:
  push:
    branches: [cd]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # - name: Checkout actions-oidc-debugger
      #   uses: actions/checkout@v3
      #   with:
      #     repository: github/actions-oidc-debugger
      #     ref: main
      #     # token: ${{ secrets.your-checkout-token }}
      #     path: ./.github/actions/actions-oidc-debugger
      # - name: Debug OIDC Claims
      #   uses: ./.github/actions/actions-oidc-debugger
      #   with:
      #     audience: '${{ github.server_url }}/${{ github.repository_owner }}'

      - name: Check out repo
        uses: actions/checkout@v4
        with:
          path: checkout-prefix
      - name: Install firebase-tools
        run: npm install -g firebase-tools
      # - name: Authenticate to Google
      #   uses: 'google-github-actions/auth@v2'
      #   with:
      #     credentials_json: ${{ secrets.GCP_SA_KEY }}
      #     create_credentials_file: true
      #     export_environment_variables: true
      #     cleanup_credentials: true
      - name: Authenticate to Google
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/705985154569/locations/global/workloadIdentityPools/kipr-github-identity-pool/providers/github'
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: true
      - name: Install dependencies
        run: npm install
        working-directory: checkout-prefix
      - name: Build
        run: npm run build
        working-directory: checkout-prefix
      # - name: Output directory
      #   run: ls
      # - name: Output checkout directory
      #   run: ls checkout-prefix
      - name: Deploy functions
        run: npm run deploy
        working-directory: checkout-prefix
      - name: Output firebase debug log
        if: always()
        run: cat firebase-debug.log
        working-directory: checkout-prefix