name: Deploy to Google Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      # Needed to produce an OIDC token, which is used for Workload Identity Federation with Google Cloud
      id-token: write
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          path: checkout-prefix
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install firebase-tools
        run: npm install -g firebase-tools
      - name: Authenticate to Google
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_ADDRESS }}
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: true
      - name: Install dependencies
        run: npm install
        working-directory: checkout-prefix
      - name: Build
        run: npm run build
        working-directory: checkout-prefix
      - name: Deploy functions
        id: deployFunctions
        run: npm run deploy
        working-directory: checkout-prefix
      - name: Output firebase debug log on deployment failure
        if: always() && (steps.deployFunctions.outcome == 'failure')
        run: cat firebase-debug.log
        working-directory: checkout-prefix