name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          path: checkout-prefix
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
        working-directory: checkout-prefix
      - name: Build
        run: npm run build
        working-directory: checkout-prefix
      - name: Run linter
        run: npm run lint
        working-directory: checkout-prefix